---
- name: Apache_httpd | Template httpd.conf
  template:
    src: apache/conf/httpd.conf.j2
    dest: "{{ apache_install_dir }}/conf/httpd.conf"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
  notify: Restart Apache

- name: Apache_httpd | Create additional configuration folders
  file:
    dest: "{{ apache_install_dir }}/conf/{{ item }}"
    state: directory
  with_items:
    - "{{ apache_additional_config_folders }}"

- name: Apache_httpd | Ensure logs folder exists
  file:
    dest: "{{ apache_logs_dir }}"
    state: directory
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0755

- name: Apache_httpd | Copy sites-available templates (provided by playbooks)
  template:
    src: "{{ item }}"
    dest: "{{ apache_install_dir }}/conf/sites-available/{{ item | basename }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0640
  with_fileglob:
    - "{{ apache_sites_available_template_path }}/*"
  notify: Restart Apache

- name: Apache_httpd | Add symlink in sites-enabled
  file:
    src: "{{ apache_install_dir }}/conf/sites-available/{{ item }}.conf"
    dest: "{{ apache_install_dir }}/conf/sites-enabled/{{ item }}.conf"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0640
    state: link
  with_items:
    - "{{ apache_sites_enabled }}"
  notify: Restart Apache

- name: Apache_httpd | Create virtualhost folders
  file:
    dest: "{{ apache_document_root }}/{{ item }}"
    state: directory
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0755
  with_items:
    - "{{ apache_sites_enabled }}"

- name: Apache_httpd | Copy virtualhost files (provided by playbooks)
  copy:
    src: "{{ item.src }}"
    dest: "{{ apache_document_root }}/{{ item.path }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0755
  with_filetree: "{{ apache_virtualhosts_files_path }}/"
  when: item.state == 'file'
  notify: Restart Apache

- name: Apache_httpd | Template rewrites file (provided by playbooks)
  template:
    src: "{{ item }}"
    dest: "{{ apache_rewrites_template_dest_folder }}/{{ item | basename | splitext |first }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0644
  notify: Restart Apache
  with_fileglob: "{{ apache_rewrites_template_src_folder }}/*"

- name: Apache_httpd | Template apache2.service
  template:
    src: apache/service/apache2.service.j2
    dest: /lib/systemd/system/apache2.service
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
  notify: Restart Apache

- name: Apache_httpd | Template logrotate
  template:
    src: apache/logrotate.j2
    dest: /etc/logrotate.d/apache2
    mode: 0644
  when: apache_logrotate_enabled

- name: Apache_httpd | Create a crontab for logrotate
  cron:
    name: "Logrotate"
    hour: "{{ apache_logrotate_cron_settings.hour}}"
    minute: "{{ apache_logrotate_cron_settings.minute }}"
    user: "{{ apache_logrotate_cron_settings.user }}"
    job: "/usr/sbin/logrotate /etc/logrotate.conf > /dev/null 2>&1"
  when: apache_logrotate_enabled
