---

- name: Apache_httpd | Template httpd.conf
  template:
    src: conf/httpd.conf.j2
    dest: "{{ apache_install_dir }}/conf/httpd.conf"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    # mode:
  notify: Restart Apache

- name: Apache_httpd | Create sites-available and sites-enabled folders
  file:
    dest: "{{ apache_install_dir }}/conf/{{ item }}"
    state: directory
  with_items:
    - sites-available
    - sites-enabled

- name: Apache_httpd | Copy sites-available templates (provided by playbooks)
  template:
    src: "{{ item }}"
    dest: "{{ apache_install_dir }}/conf/sites-available/{{ item | basename }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0644
  register: new_templates
  with_fileglob:
    - "{{ apache_sites_available_template_path }}/*"
  notify: Restart Apache

- name: Apache_httpd | Add symlink in sites-enabled
  file:
    src: "{{ apache_install_dir }}/conf/sites-available/{{ item }}"
    dest: "{{ apache_install_dir }}/conf/sites-enabled/{{ item }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0644
    state: link
  with_items:
    - "{{ apache_sites_enabled }}"
  notify: Restart Apache
  when: new_templates.changed
  tags:
    - skip_ansible_lint

- name: Apache_httpd | Template apache2.service
  template:
    src: service/apache2.service.j2
    dest: /lib/systemd/system/apache2.service
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    # mode:
  notify: Restart Apache
