- name: Apache_httpd | Install mod_jk prerequisites
  apt:
    package: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
  with_items: "{{ apache_modjk_prerrequisites }}"

- name: Apache_httpd | Download mod_jk
  unarchive:
    src: "{{ apache_modjk_url }}"
    dest: "{{ apache_modjk_download_dir }}"
    remote_src: yes
  changed_when: false

- name: Apache_httpd | Create configure script
  command: ./buildconf.sh
  args:
    chdir: "{{ apache_modjk_build_dir }}"
  changed_when: false

- name: Apache_httpd | Configure mod_jk
  command: ./configure -with-apxs={{ apache_install_dir }}/bin/apxs
  args:
    chdir: "{{ apache_modjk_build_dir }}"
  changed_when: false

- name: Apache_httpd | Make mod_jk
  make:
    chdir: "{{ apache_modjk_build_dir }}"

- name: Apache_httpd | Copy mod_jk to Apache modules folder
  template:
    src: "{{ apache_modjk_build_dir }}/apache-2.0/mod_jk.so"
    dest: "{{ apache_install_dir }}/modules/mod_jk.so"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    remote_src: true

- name: Apache_httpd | Copy mod_jk configuration file
  template:
    src: "{{ apache_modjk_playbook_files_dir }}/{{ apache_modjk_conf_file }}"
    dest: "{{ apache_install_dir }}/conf/extra/{{ apache_modjk_conf_file }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0640
  when: apache_modjk_conf

- name: Apache_httpd | Copy mod_jk workers properties file
  copy:
    src: "{{ apache_modjk_playbook_files_dir }}/{{ apache_modjk_workers_properties_file }}"
    dest: "{{ apache_install_dir }}/conf/extra/{{ apache_modjk_workers_properties_file }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0640
  when: apache_modjk_workers_properties
